In [1]:
import numpy as np

## **DataTypes and Attributes** 

In [2]:
#NumPy's main data type is an array of n dimensions.
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.shape
# Shape gives the number of rows and columns an array contains in the format of (number of rows, number of columns). For 1-D arrays, shape = (Number of elements, )

(3,)

In [5]:
a1.ndim
# ndim gives the number of dimensions of an array

1

In [6]:
a1.size
# Size gives us the number of elements present in the array

3

In [7]:
import pandas as pd
df = pd.DataFrame(a1)
df
# The 0 on the top is row, the numbers 0,1,2 on the side are columns.

0
0  1
1  2
2  3

## **Creating NumPy arrays**

In [9]:
ones = np.ones((2, 3))
ones
#Return a new array of given shape and type, filled with ones. Press shift+tab while inside the innermost parentheses for more info. We have only given shape here. Type is optional.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
zeros = np.zeros((2,3))
zeros
#Same function as ones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
range_array = np.arange(0, 10, 2)
range_array
#Return evenly spaced values within a given interval. The numbers inside the parentheses are in the format of (start, stop, step). Go from 0 to 10 by skipping 2 numbers.

array([0, 2, 4, 6, 8])

In [12]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array
#Creates a random array of the given size which consists of integers which are between the 2 given integers.

array([[9, 7, 5, 1, 5],
       [0, 2, 3, 6, 2],
       [8, 7, 2, 9, 8]])

In [13]:
random_array.size, random_array.shape

(15, (3, 5))

In [14]:
random_array_2 = np.random.random((5, 3))
random_array_2
#Creates a random array of the given shape consisting of values between 0 and 1

array([[0.05867231, 0.14835229, 0.0708516 ],
       [0.54787383, 0.42499695, 0.70291532],
       [0.47407267, 0.66610214, 0.53508927],
       [0.17398088, 0.87353648, 0.54469069],
       [0.25277696, 0.91347593, 0.53467447]])

In [25]:
np.random.seed(7)
random_array_3 = np.random.random((5, 3))
random_array_3
#Whenever we set the random seed to a specific number. We will get the same aray everytime with no change at all.

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [26]:
np.unique(random_array)
#Gives us the unique elements present in any array

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [27]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4


array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [28]:
a1, ones

(array([1, 2, 3]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [29]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [30]:
a1 + ones

array([2., 3., 4.])

## **Manipulating Arrays**

For 2 arrays to be multiplied correctly, they should both have the same shape or their shape should be 1.

In [31]:
a1 ** 2

array([1, 4, 9])

You can also use methods like np.square() or np.add() also

In [32]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [33]:
np.log(a1), np.exp(a1)

(array([0.        , 0.69314718, 1.09861229]),
 array([ 2.71828183,  7.3890561 , 20.08553692]))

In [34]:
sum(a1)
#This is a Python method

6

In [35]:
np.sum(a1)
#This is a NumPy method

6

**Use NumPy methods on NumPy arrays and Python methods on Python datatypes**

In [36]:
massive_array = np.random.random(1000)
massive_array.size

1000

In [37]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [38]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

86.6 μs ± 4.63 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.27 μs ± 358 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


As you can see, NumPy's sum method is much faster


In [39]:
np.mean(a1)

2.0

In [40]:
np.max(a1), np.min(a1)

(3, 1)

In [41]:
#Variance = measure of the average degree to which the each number is different from the mean. Standard deviation is the square root of variance.
np.var(a1)

0.6666666666666666

## **Reshape and Transpose**

**Multiplication of 2 arrays can take place only when their dimensions are compatible.Two dimensions are compatible when 
they are equal or one of them is 1.**


Transpose switches the columns into rows and the rows into columns


## **Dot Producst**

In [47]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [48]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [49]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [50]:
mat1 * mat2
#Element-wise multiplication, in this, you multiply each element of the matrix with the element present at the corresponding position in the other matrix. Observe the top rows of mat1, mat2 and the resulting product.

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

**Dot product is same as we do matrix multiplication in Maths**

In [51]:
mat1.T #Transpose of matrix1

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [52]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [53]:
mat3.shape


(5, 5)

## **Dot Product Example (Nut Butter Sales)**

In [54]:
np.random.seed(0)
#Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [55]:
#Create weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [57]:
#Create prices array
prices = np.array([10, 8, 12])
prices.shape

(3,)

In [59]:
#Create butter_prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"],columns=["Almond butter", "Peanut Butter", "Cashew Butter"] )
#We need to reshape the prices array because it's shape is (3, ) and our dataframe is desgined to have a shape of (1, 3)
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [60]:
sales_amounts.shape

(5, 3)

**Since the shape of the prices array is (1, 3) and the shape of the sales_amounts array is (5, 3), for calculating the dot product and hence finding the total sales per day, we would need to take transpose of the sales_amount array.**

In [61]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [63]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [64]:
daily_sales = weekly_sales.dot(butter_prices.T)

In [65]:
daily_sales

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [66]:
daily_sales.shape

(5, 1)

In [67]:
weekly_sales["Total"] = daily_sales
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total
Mon               12             15              0    240
Tue                3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

In [68]:
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [69]:
random_array

array([[9, 7, 5, 1, 5],
       [0, 2, 3, 6, 2],
       [8, 7, 2, 9, 8]])

In [70]:
np.sort(random_array)
#Sorts the number in each row

array([[1, 5, 5, 7, 9],
       [0, 2, 2, 3, 6],
       [2, 7, 8, 8, 9]])

In [71]:
np.argsort(random_array)
#Returns the indices that would sort an array.

array([[3, 2, 4, 1, 0],
       [0, 1, 4, 2, 3],
       [2, 1, 0, 4, 3]], dtype=int64)

<img src = "Screenshot (192).png"/>

In [4]:
from matplotlib.image import imread
image = imread("Screenshot (192).png")
print(type(image))

<class 'numpy.ndarray'>


In [5]:
image

array([[[0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        ...,
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ]],

       [[0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        ...,
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ]],

       [[0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        ...,
        [0.08235294, 0.15686275, 0.3137255 , 1.        ],
        [0.08235294, 0.156862

In [6]:
image.size, image.shape, image.ndim

(8294400, (1080, 1920, 4), 3)

<img src = "Screenshot (176).png"/>

In [7]:
screenshot = imread("Screenshot (176).png")
print(type(screenshot))

<class 'numpy.ndarray'>


In [8]:
screenshot

array([[[0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        ...,
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ]],

       [[0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        ...,
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ]],

       [[0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        ...,
        [0.13333334, 0.1254902 , 0.10196079, 1.        ],
        [0.13333334, 0.125490